name: Build Windows Base Training AMI

# Controls when the action will run. 

on:
  # Triggers the workflow on push or pull request events but only for the main branch
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]
  workflow_dispatch:
  schedule:
  - cron: '1 1 * * 0'  # once a week on sunday 

jobs:
  packer:
    runs-on: ubuntu-20.04
    name: Build Temp Ubuntu Env for Build Pipeline
    steps:
    - name: Branch name
      run: echo running on branch ${GITHUB_REF##*/}
      
    - name: Checkout files from commit tree
      uses: actions/checkout@v2

    - name: Public IP of Ubuntu Instance of Build Pipeline
      id: ip
      uses: haythem/public-ip@v1.2
 
# This take the our private ssh key and ships it to the ubuntu instance, that will then provision AWS  
    - name: Move SSH key to Ephemeral Ubuntu Instance 
      run: |
          mkdir /home/runner/work/_temp/_github_home
          echo "$SSH_PRIVATE_KEY" > /home/runner/work/_temp/_github_home/elastic_training
      env:
          SSH_PRIVATE_KEY: ${{ secrets.KEY_FILE }}
