name: Build Windows Base Training AMI

# Controls when the action will run. 

on:
  # Triggers the workflow on push or pull request events but only for the main branch
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]
  workflow_dispatch:
  schedule:
  - cron: '1 1 * * 0'  # once a week on sunday 

jobs:
  packer:
    runs-on: ubuntu-20.04
    name: Build Temp Ubuntu Env for Build Pipeline
    steps:
    - name: Branch name
      run: echo running on branch ${GITHUB_REF##*/}
      
    - name: Checkout files from commit tree
      uses: actions/checkout@v2

    - name: Public IP of Ubuntu Instance of Build Pipeline
      id: ip
      uses: haythem/public-ip@v1.2
 
# This take the our private ssh key and ships it to the ubuntu instance, that will then provision AWS  
    - name: Move SSH key to Ephemeral Ubuntu Instance 
      run: |
          mkdir /home/runner/work/_temp/_github_home
          echo "$SSH_PRIVATE_KEY" > /home/runner/work/_temp/_github_home/elastic_training
      env:
          SSH_PRIVATE_KEY: ${{ secrets.KEY_FILE }}

    - name: Stand up an EC2 instance for us to use
      run: |
          echo "C5_INSTANCE_ID=$(aws ec2 run-instances \
          --image-id ami-0c9354388bb36c088 \
          --instance-type c5.large \
          --security-group-ids sg-0b01df679b9ce6126 \
          --key-name elastic_training \
          --block-device-mappings DeviceName=/dev/sda1,Ebs={VolumeSize=100}| jq -r '.Instances[0] | .InstanceId')" >> $GITHUB_ENV
      env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-central-1
      
    - name: Repeat ID
      run: echo "${{ env.C5_INSTANCE_ID }}"

    - name: Grab DNS name for it
      run: |
          echo "C5_REMOTE_HOST=$(aws ec2 describe-instances --instance-ids ${{ env.C5_INSTANCE_ID }} | jq -r '.Reservations[0].Instances[0] | .PublicDnsName')" >> $GITHUB_ENV 
      env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-central-1
          RUNNER_IPV4: ${{ steps.ip.outputs.ipv4 }}
          KEY_FILE: ${{ secrets.KEY_FILE }}
          EC_AUTH: ${{ secrets.EC_AUTH}}
          EC_ID: ${{ secrets.EC_ID }}
          SSH_FILE: ${{ secrets.SSH_FILE }}
          AWS_MAX_ATTEMPTS: 90
          AWS_POLL_DELAY_SECONDS: 60

    - name: Repeat Host
      run: echo "${{ env.C5_REMOTE_HOST }}"


    - name: Checkout the files
      uses: actions/checkout@v2

    - name: Sleep for 30 seconds while we wait for the instance to come up
      uses: jakejarvis/wait-action@master
      with:
        time: '30s'

    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.KEY_FILE }}
        REMOTE_HOST: ${{ env.C5_REMOTE_HOST }}
        REMOTE_USER: ubuntu
        TARGET: /tmp
      
    
    - name: Install QEMU packages
      uses: appleboy/ssh-action@master
      with:
        host: ${{ env.C5_REMOTE_HOST }}
        username: ubuntu
        key: ${{ secrets.KEY_FILE }}
        port: 22
        script: |
          apt-get update
          apt-get install qemu virt-manager
    
    - name: Install Packer
      uses: appleboy/ssh-action@master
      with:
        host: ${{ env.C5_REMOTE_HOST }}
        username: ubuntu
        key: ${{ secrets.KEY_FILE }}
        port: 22
        script: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          apt-get update && sudo apt-get install packer

    - name: Stand up Windows instance
      uses: appleboy/ssh-action@master
      with:
        host: ${{ env.C5_REMOTE_HOST }}
        username: root
        key: ${{ secrets.KEY_FILE }}
        port: 22
        script: |
          cd /tmp
          packer build windows.json